data <- read.table("household_power_consumption.txt",header = TRUE, sep =";", na.strings ="?", stringsAsFactors=FALSE)
data$Date<-as.Date(data$Date,'%d/%m/%Y')
data <-subset(data, Date == "2007-02-01" | Date == "2007-02-02" )
GAP <- as.numeric(data$Global_active_power)
hist(GAP, col= "red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.copy(png,'plot1.png)
dev.off()
