data <- read.table("household_power_consumption.txt",header = TRUE, sep =";", na.strings ="?", stringsAsFactors=FALSE)
data$Date<-as.Date(data$Date,'%d/%m/%Y')
data <-subset(data, Date == "2007-02-01" | Date == "2007-02-02" )
time <-paste(data$Date, data$Time, sep=" ")
time <- strptime(time, "%Y-%m-%d %H:%M:%S")
Sub_metering_1 <- as.numeric(data$Sub_metering_1)
Sub_metering_2 <- as.numeric(data$Sub_metering_2)
Sub_metering_3 <- as.numeric(data$Sub_metering_3)
plot(time, Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(time, Sub_metering_2, type="l", col="red")
lines(time, Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.copy(png, file="plot3.png", height=480, width=480)
dev.off()
