data <- read.table("household_power_consumption.txt",header = TRUE, sep =";", na.strings ="?", stringsAsFactors=FALSE)
data$Date<-as.Date(data$Date,'%d/%m/%Y')
data <-subset(data, Date == "2007-02-01" | Date == "2007-02-02" )
time <-paste(data$Date, data$Time, sep=" ")
time <- strptime(time, "%Y-%m-%d %H:%M:%S")
GAP <- as.numeric(data$Global_active_power)
png(filename = "plot2.png", width = 480, height = 480, units = "px")
plot(time,GAP,pch=20,cex=0.1,xlab="", ylab="Global Active Power (kilowatts)", type="l",lwd=1)
dev.off()
